// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const green_man = { y: 0, x: 16, h: 16, w: 16, url: url, };
export const red_man = { y: 0, x: 32, h: 16, w: 16, url: url, };
export const nine_slice = { y: 0, x: 0, center: { y: 2, x: 2, w: 6, h: 5, }, h: 11, w: 10, url: url, };