// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const pawn_blue = { w: 11, x: 0, pivot: { y: 6, x: 5, }, h: 16, y: 0, url: url, };
export const castle_blue = { w: 11, x: 11, h: 16, y: 0, url: url, };
export const king_blue = { w: 11, x: 22, h: 16, y: 0, url: url, };
export const queen_blue = { w: 11, x: 33, h: 16, y: 0, url: url, };
export const bishop_blue = { w: 11, x: 44, h: 16, y: 0, url: url, };
export const knight_blue = { w: 11, x: 55, h: 16, y: 0, url: url, };
export const pawn_red = { w: 11, x: 0, h: 16, y: 16, url: url, };
export const castle_red = { w: 11, x: 11, h: 16, y: 16, url: url, };
export const king_red = { w: 11, x: 22, h: 16, y: 16, url: url, };
export const queen_red = { w: 11, x: 33, h: 16, y: 16, url: url, };
export const bishop_red = { w: 11, x: 44, h: 16, y: 16, url: url, };
export const knight_red = { w: 11, x: 55, h: 16, y: 16, url: url, };
export const panel_blue = { w: 16, x: 0, center: { w: 12, x: 2, y: 2, h: 12, }, h: 16, y: 32, url: url, };
export const panel_red = { w: 16, x: 16, center: { w: 12, x: 2, y: 2, h: 12, }, h: 16, y: 32, url: url, };