function exportSpriteSheet(spr)
  local texturePath = string.gsub(spr.filename, ".aseprite", ".png")
  local modulePath = string.gsub(spr.filename, ".aseprite", ".ts")
  local importUrl = "./" .. texturePath:match("^.+/(.+)$")

  local lines = {
    "// Generated by 'Export TypeScript Sprites' Aseprite Extension",
    string.format('import url from "%s"', importUrl),
  }

  for i, slice in ipairs(spr.slices) do
    local bounds = slice.bounds;
    local rect = {bounds.x, bounds.y, bounds.width, bounds.height}
    local line = string.format(
      'export const %s = {x:%d,y:%d,w:%d,h:%d,url};',
      slice.name,
      slice.bounds.x,
      slice.bounds.y,
      slice.bounds.width,
      slice.bounds.height
    )
    table.insert(lines, line)
  end

  local src = table.concat(lines, "\n")
  local file = io.open(modulePath, "w")
  file:write(src)
  file:close()

  app.command.ExportSpriteSheet{
    ui=false,
    textureFilename=texturePath,
  }
end

function init(plugin)
  plugin:newCommand{
    id="ExportTypeScriptSprites",
    title="Export TypeScript",
    group="file_export",
    onclick=function()
      exportSpriteSheet(app.activeSprite)
    end
  }
end
